# Generated by Django 5.0.6 on 2024-07-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
