# Generated by Django 5.0.6 on 2024-07-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
